#!/bin/bash

#SBATCH --job-name stencil
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --time 00:15:00
#SBATCH --partition veryshort
#SBATCH --output stencil.out
#SBATCH --exclusive

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
srun ./stencil 1024 1024 100
